const ArticleActionTypes = {

  ADD_ARTICLE_START: 'ADD_ARTICLE_START', 
  ADD_ARTICLE_SUCCESS: 'ADD_ARTICLE_SUCCESS', 
  ADD_ARTICLE_FAILURE: 'ADD_ARTICLE_FAILURE', 

  GET_ARTICLE_LIST_START: 'GET_ARTICLE_LIST_START', 
  GET_ARTICLE_LIST_SUCCESS: 'GET_ARTICLE_LIST_SUCCESS', 
  GET_ARTICLE_LIST_FAILURE: 'GET_ARTICLE_LIST_FAILURE',
  
  POINT_ARTICLE_START: 'POINT_ARTICLE_START', 
  POINT_ARTICLE_SUCCESS: 'POINT_ARTICLE_SUCCESS', 
  POINT_ARTICLE_FAILURE: 'POINT_ARTICLE_FAILURE',

  GET_ARTICLE_START: 'GET_ARTICLE_START', 
  GET_ARTICLE_SUCCESS: 'GET_ARTICLE_SUCCESS', 
  GET_ARTICLE_FAILURE: 'GET_ARTICLE_FAILURE',

  DELETE_ARTICLE_START: 'DELETE_ARTICLE_START', 
  DELETE_ARTICLE_SUCCESS: 'DELETE_ARTICLE_SUCCESS', 
  DELETE_ARTICLE_FAILURE: 'DELETE_ARTICLE_FAILURE',
}

export default ArticleActionTypes;